apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: laravel-k8s-prod
  labels:
    app: laravel-k8s-app
    env: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel-k8s-app
      env: prod
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: laravel-k8s-app
        env: prod
    spec:
      # Init containers are exactly like regular containers, except:
      # - Init containers always run to completion.
      # - Each init container must complete successfully before the next one starts.
      # - Regular container does not start until init container finishes.
      initContainers:
      - name: deploy
        image: ghcr.io/yallungrai277/laravel-k8s-cli:latest
        imagePullPolicy: IfNotPresent
        command:
        - /bin/sh
        - -c
        # On kuberenetes context, When using PV and PVC, it overrides the container file system permissions and removes folder. 
        # Hence, we create folders and set those permissions here.        
        - |
          mkdir -p storage/app storage/framework/cache storage/framework/sessions storage/framework/testing storage/framework/views storage/logs && \
          chown -R www-data:www-data /var/www/html/storage && \
          chmod -R 777 /var/www/html/storage && \
          cd /var/www/html && \
          chmod +x ./scripts/post_deploy.sh && \
          ./scripts/post_deploy.sh
        envFrom:
        - configMapRef:
            name: app-config-map
        - secretRef:
            name: app-secrets
        volumeMounts:
        - name: app-volume
          mountPath: /var/www/html/storage

      containers:
      # App container
      - name: app
        image: ghcr.io/yallungrai277/laravel-k8s-app:latest
        envFrom:
        - configMapRef:
            name: app-config-map
        - secretRef:
            name: app-secrets
        # Shorter syntax above. We can also do below but longer syntax and one by one.
        # env:
        # - name: DB_HOST
        #   valueFrom:
        #     configMapKeyRef:
        #       name: app-config-map
        #       key: DB_HOST

        volumeMounts:
        # App volume such as logs, cache etc...
        - name: app-volume
          mountPath: /var/www/html/storage
        ports:
        - containerPort: 9000
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"

      # Web container
      - name: nginx
        image: ghcr.io/yallungrai277/laravel-k8s-nginx:latest
        ports:
        - containerPort: 80
        imagePullPolicy: IfNotPresent
        volumeMounts:
        # Static assets required by nginx to serve images.
        - name: app-volume
          mountPath: /var/www/html/public/storage
          subPath: app/public # Sub path is the path inside app-volume, we want to mount from app/public volume subpath on above container mount path.
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"

      imagePullSecrets:
      - name: ghcr-secret
      volumes:
      # App volume such as logs, cache, assets etc...
      - name: app-volume
        persistentVolumeClaim:
          claimName: app-pvc-prod

---
# Service used to expose app outside cluster, not a recommended way of doing
# but here for testing. Ingress is also used refer to README.md
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: laravel-k8s-prod
  labels:
    app: laravel-k8s-app
    env: prod
spec:
  selector:
    app: laravel-k8s-app
    env: prod
  type: NodePort
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30000
