apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: laravel-k8s-mysql
  namespace: laravel-k8s-prod
  labels:
    app: laravel-k8s-prod
    env: prod
    type: database
spec:
  selector:
    matchLabels:
      app: laravel-k8s-prod
      env: prod
      type: database
  serviceName: mysql-headless-prod
  template:
    metadata:
      labels:
        app: laravel-k8s-prod
        env: prod
        type: database
    spec:
      containers:
      - name: mysql
        image: mariadb:10.11.4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
        env:
        - name: MARIADB_DATABASE
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DB_DATABASE

        - name: MARIADB_USER
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DB_USERNAME

        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DB_PASSWORD

        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DB_ROOT_PASSWORD

        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql

      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-pvc-prod

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-headless-prod
  namespace: laravel-k8s-prod
spec:
  selector:
    app: laravel-k8s-prod
    env: prod
    type: database
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  clusterIP: None


