apiVersion: v1
kind: ConfigMap
metadata:
  namespace: laravel-k8s-prod
  name: app-config-map
data:
  # Overrides .env values. Add if needed.
  APP_NAME: laravel-k8s
  APP_DEBUG: "false"
  APP_ENV: production
  APP_URL: http://laravel-k8s.test
  DB_HOST: mysql-headless-prod
  DB_CONNECTION: mysql
  DB_PORT: "3306"
  REDIS_HOST: redis-headless-prod
  REDIS_PORT: "6379"
  MAIL_MAILER: smtp
  MAIL_HOST: sandbox.smtp.mailtrap.io
  MAIL_PORT: "2525"
  # Configure proper mail provider here.
  MAIL_USERNAME: d0add9dc8f7a99
  MAIL_PASSWORD: d37813786effe8
