apiVersion: v1
kind: ConfigMap
metadata:
  namespace: laravel-k8s-prod
  name: app-config-map
data:
  # Overrides .env values. Add if needed.
  APP_NAME: laravel-k8s
  # Set app_debug to true and app_env to production only if you are running on https, because simply turning these values to production will affect laravel signed urls
  # and it will not work, because under the hood laravel will sign the url forcing https scheme checking these values even if you are running on http.
  # Hence, the signature and the url will not match.
  APP_DEBUG: "true"
  APP_ENV: local
  APP_URL: http://laravel-k8s.test
  DB_HOST: mysql-headless-prod
  DB_CONNECTION: mysql
  DB_PORT: "3306"
  REDIS_HOST: redis-headless-prod
  REDIS_PORT: "6379"
  MAIL_MAILER: smtp
  MAIL_HOST: sandbox.smtp.mailtrap.io
  MAIL_PORT: "2525"
  # Configure proper mail provider here.
  MAIL_USERNAME: d0add9dc8f7a99
  MAIL_PASSWORD: d37813786effe8
