apiVersion: v1
kind: Service
metadata:
  name: app-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: laravel-k8s-app
    env: prod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
