apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-prod
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    #  https://minikube.sigs.k8s.io/docs/handbook/persistent_volumes/
    path: /data/mysql/

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-prod
  namespace: laravel-k8s-prod
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
