apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv-prod
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    #  https://minikube.sigs.k8s.io/docs/handbook/persistent_volumes/
    path: /data/redis/

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc-prod
  namespace: laravel-k8s-prod
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
