# kubectl create secret docker-registry --dry-run=true docker-regcred \
# --docker-server=https://index.docker.io/v1/ \
# --docker-username=xxx \
# --docker-password=xxx \
# --docker-email=yourmail@yourdomain.com \
# --namespace=xxx \
# -o yaml > docker-secret.yaml

# After running above command paste the contents of file here. Note that namespace is optional.
# See official k8s documentation on what this actual secret looks like on decoded version.
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2doY3IuaW8iOnsidXNlcm5hbWUiOiJ5YWxsdW5ncmFpMjc3IiwicGFzc3dvcmQiOiJnaHBfV0pmRlRIOUltaFFqTGtFbkI3ZXQzY3Z1NGNKVGFKNFVNTnp1IiwiZW1haWwiOiJ5YWxsdW5ncmFpMjc3QGdtYWlsLmNvbSIsImF1dGgiOiJlV0ZzYkhWdVozSmhhVEkzTnpwbmFIQmZWMHBtUmxSSU9VbHRhRkZxVEd0RmJrSTNaWFF6WTNaMU5HTktWR0ZLTkZWTlRucDEifX19
kind: Secret
metadata:
  name: ghcr-secret
type: kubernetes.io/dockerconfigjson
